CONFIG = {
    'controls': (
        #'Wemo',
        #'KuappiGPIO',
        'ValloxControl',
        #'AlarmControl',
    ),
    #'sensor': 'W1Temp',
    'sensor': 'MiTemp',
    #'sensor': 'MqttSensor',
    'mqtt_client': 'zigbee2mqtt/0x00158d00023278d1',
    'mqtt_client_name': 'Kuappi',
    #'decision': 'FridgeDecision',
    'decision': 'ValloxDecision',
    #'decision': 'FreezerDecision',
    'summer_mode': False,
    'use_redis': False,
    'polling_freq': 60,
    'mitemp_addr': '58:2D:34:34:4C:3E',
    'mitemp_cache_timeout': 300,
    'gpio_pin': 22,
    'log_file': '/tmp/kuappi.log',
}
